version: '3.4'

services:
  app:
    image: nodets-quickstart
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
